name: collegeadmissionhelper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2
  english_words: ^4.0.0
  provider: ^6.1.2


  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./lib/assets/app-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "./lib/assets/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - ./lib/assets/app-icon.png